/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancones;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Enrique
 */
public class b_Usuarios extends javax.swing.JFrame {
            private boolean b;
    /**
     * Creates new form b_Usuarios
     */
    public b_Usuarios() {
        initComponents();
        this.password.setVisible(false);
        this.user.setVisible(false);
        this.user_txt.setVisible(false);
        this.pass_txt.setVisible(false);
        this.Ejecutivo_pic2.setVisible(false);
        this.Cliente_pic2.setVisible(false);
        this.Cajero_pic2.setVisible(false);
        this.ejec_txt2.setVisible(false);
        this.caje_txt2.setVisible(false);
        this.clie_txt2.setVisible(false);
        this.Aceptar.setVisible(false);
        nip1.setVisible(false);
        nc1.setVisible(false);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Gerente_pic = new javax.swing.JLabel();
        Ejecutivo_pic2 = new javax.swing.JLabel();
        Cajero_pic2 = new javax.swing.JLabel();
        Ejecutivo_pic = new javax.swing.JLabel();
        Cliente_pic2 = new javax.swing.JLabel();
        Cliente_pic = new javax.swing.JLabel();
        Cajero_pic = new javax.swing.JLabel();
        seleccion = new javax.swing.JLabel();
        gere_txt = new javax.swing.JLabel();
        ejec_txt2 = new javax.swing.JLabel();
        clie_txt2 = new javax.swing.JLabel();
        caje_txt2 = new javax.swing.JLabel();
        ejec_txt = new javax.swing.JLabel();
        caje_txt = new javax.swing.JLabel();
        clie_txt = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        user = new javax.swing.JTextField();
        user_txt = new javax.swing.JLabel();
        pass_txt = new javax.swing.JLabel();
        loguito = new javax.swing.JLabel();
        loguito1 = new javax.swing.JLabel();
        Aceptar = new javax.swing.JButton();
        nip1 = new javax.swing.JLabel();
        nc1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 550));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/usuario.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 20, 350, 90);

        Gerente_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/gerente.png"))); // NOI18N
        Gerente_pic.setToolTipText("GERENTE");
        Gerente_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Gerente_picMouseClicked(evt);
            }
        });
        getContentPane().add(Gerente_pic);
        Gerente_pic.setBounds(50, 200, 130, 160);

        Ejecutivo_pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/ejecutivo.png"))); // NOI18N
        Ejecutivo_pic2.setToolTipText("EJECUTIVO");
        getContentPane().add(Ejecutivo_pic2);
        Ejecutivo_pic2.setBounds(50, 200, 140, 170);

        Cajero_pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/cajero.png"))); // NOI18N
        Cajero_pic2.setToolTipText("CAJERO");
        getContentPane().add(Cajero_pic2);
        Cajero_pic2.setBounds(50, 200, 140, 160);

        Ejecutivo_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/ejecutivo.png"))); // NOI18N
        Ejecutivo_pic.setToolTipText("EJECUTIVO");
        Ejecutivo_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ejecutivo_picMouseClicked(evt);
            }
        });
        getContentPane().add(Ejecutivo_pic);
        Ejecutivo_pic.setBounds(240, 200, 140, 170);

        Cliente_pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/cliente.png"))); // NOI18N
        Cliente_pic2.setToolTipText("CAJERO");
        Cliente_pic2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cliente_pic2MouseClicked(evt);
            }
        });
        getContentPane().add(Cliente_pic2);
        Cliente_pic2.setBounds(60, 200, 140, 160);

        Cliente_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/cliente.png"))); // NOI18N
        Cliente_pic.setToolTipText("CAJERO");
        Cliente_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cliente_picMouseClicked(evt);
            }
        });
        getContentPane().add(Cliente_pic);
        Cliente_pic.setBounds(590, 210, 140, 160);

        Cajero_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/cajero.png"))); // NOI18N
        Cajero_pic.setToolTipText("CAJERO");
        Cajero_pic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cajero_picMouseClicked(evt);
            }
        });
        getContentPane().add(Cajero_pic);
        Cajero_pic.setBounds(400, 210, 140, 160);

        seleccion.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        seleccion.setForeground(new java.awt.Color(0, 102, 0));
        seleccion.setText("Seleccione su tipo de usuario:");
        getContentPane().add(seleccion);
        seleccion.setBounds(280, 150, 230, 18);

        gere_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gere_txt.setForeground(new java.awt.Color(0, 102, 51));
        gere_txt.setText("Gerente");
        getContentPane().add(gere_txt);
        gere_txt.setBounds(100, 370, 60, 17);

        ejec_txt2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ejec_txt2.setForeground(new java.awt.Color(0, 102, 51));
        ejec_txt2.setText("Ejecutivo");
        getContentPane().add(ejec_txt2);
        ejec_txt2.setBounds(100, 370, 60, 17);

        clie_txt2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clie_txt2.setForeground(new java.awt.Color(0, 102, 51));
        clie_txt2.setText("Cliente");
        getContentPane().add(clie_txt2);
        clie_txt2.setBounds(100, 370, 60, 17);

        caje_txt2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        caje_txt2.setForeground(new java.awt.Color(0, 102, 51));
        caje_txt2.setText("Cajero");
        getContentPane().add(caje_txt2);
        caje_txt2.setBounds(100, 370, 60, 17);

        ejec_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ejec_txt.setForeground(new java.awt.Color(0, 102, 51));
        ejec_txt.setText("Ejecutivo");
        getContentPane().add(ejec_txt);
        ejec_txt.setBounds(280, 370, 60, 17);

        caje_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        caje_txt.setForeground(new java.awt.Color(0, 102, 51));
        caje_txt.setText("Cajero");
        getContentPane().add(caje_txt);
        caje_txt.setBounds(450, 370, 60, 17);

        clie_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clie_txt.setForeground(new java.awt.Color(0, 102, 51));
        clie_txt.setText("Cliente");
        getContentPane().add(clie_txt);
        clie_txt.setBounds(630, 370, 60, 17);

        password.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 11)); // NOI18N
        password.setForeground(new java.awt.Color(0, 102, 0));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(460, 330, 310, 30);

        user.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        user.setForeground(new java.awt.Color(0, 102, 0));
        user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(user);
        user.setBounds(460, 260, 310, 30);

        user_txt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        user_txt.setForeground(new java.awt.Color(0, 102, 51));
        user_txt.setText("User:");
        getContentPane().add(user_txt);
        user_txt.setBounds(230, 260, 200, 22);

        pass_txt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pass_txt.setForeground(new java.awt.Color(0, 102, 51));
        pass_txt.setText("Password:");
        getContentPane().add(pass_txt);
        pass_txt.setBounds(240, 330, 140, 22);

        loguito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/logochiqui.png"))); // NOI18N
        loguito.setToolTipText("EJECUTIVO");
        loguito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loguitoMouseClicked(evt);
            }
        });
        getContentPane().add(loguito);
        loguito.setBounds(690, 10, 90, 70);

        loguito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/logochiqui.png"))); // NOI18N
        loguito1.setToolTipText("EJECUTIVO");
        loguito1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loguito1MouseClicked(evt);
            }
        });
        getContentPane().add(loguito1);
        loguito1.setBounds(20, 10, 90, 70);

        Aceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Aceptar.setForeground(new java.awt.Color(0, 51, 0));
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(Aceptar);
        Aceptar.setBounds(350, 420, 110, 25);
        getContentPane().add(nip1);
        nip1.setBounds(50, 110, 100, 40);
        getContentPane().add(nc1);
        nc1.setBounds(60, 150, 110, 20);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 800, 550);

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 153));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jMenu1.setForeground(new java.awt.Color(0, 153, 0));
        jMenu1.setText("OPCIONES");
        jMenu1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jMenuItem2.setText("Atras");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jMenuItem3.setText("Usuario");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setBackground(new java.awt.Color(255, 255, 51));
        jMenuItem1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed

        
        
    }//GEN-LAST:event_passwordActionPerformed

    private void Gerente_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Gerente_picMouseClicked
        // TODO add your handling code here:
        b=false;
        this.password.setVisible(true);
        this.user.setVisible(true);
        this.user_txt.setVisible(true);
        this.pass_txt.setVisible(true);
        this.Aceptar.setVisible(true);
        this.Cajero_pic.setVisible(false);
        this.Ejecutivo_pic.setVisible(false);
        this.Cliente_pic.setVisible(false);
        this.clie_txt.setVisible(false);
        this.caje_txt.setVisible(false);
        this.ejec_txt.setVisible(false);
        user_txt.setText("Usuario: ");
        pass_txt.setText("Contrasena: ");
    }//GEN-LAST:event_Gerente_picMouseClicked

    private void Ejecutivo_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ejecutivo_picMouseClicked
        // TODO add your handling code here:
        b=false;
        this.password.setVisible(true);
        this.Aceptar.setVisible(true);
        this.user.setVisible(true);
        this.user_txt.setVisible(true);
        this.pass_txt.setVisible(true);
        this.Ejecutivo_pic2.setVisible(true);
        this.ejec_txt2.setVisible(true);
        this.Gerente_pic.setVisible(false);
        this.Cajero_pic.setVisible(false);
        this.Ejecutivo_pic.setVisible(false);
        this.caje_txt.setVisible(false);
        this.ejec_txt.setVisible(false);
        this.gere_txt.setVisible(false);
        this.Cliente_pic.setVisible(false);
        this.clie_txt.setVisible(false);
         user_txt.setText("Usuario: ");
        pass_txt.setText("Contrasena: ");
    }//GEN-LAST:event_Ejecutivo_picMouseClicked

    private void Cajero_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cajero_picMouseClicked
        // TODO add your handling code here:
        b=false;
        this.password.setVisible(true);
        this.Aceptar.setVisible(true);
        this.user.setVisible(true);
        this.user_txt.setVisible(true);
        this.pass_txt.setVisible(true);
        this.Cajero_pic2.setVisible(true);
        this.caje_txt2.setVisible(true);
        this.Gerente_pic.setVisible(false);
        this.Cajero_pic.setVisible(false);
        this.Ejecutivo_pic.setVisible(false);
        this.caje_txt.setVisible(false);
        this.ejec_txt.setVisible(false);
        this.gere_txt.setVisible(false);
        this.Cliente_pic.setVisible(false);
        this.clie_txt.setVisible(false);
         user_txt.setText("Usuario: ");
        pass_txt.setText("Contrasena: ");
    }//GEN-LAST:event_Cajero_picMouseClicked

    private void Cliente_picMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cliente_picMouseClicked
        // TODO add your handling code here:
        b=true;
        this.password.setVisible(true);
        this.Aceptar.setVisible(true);
        this.user.setVisible(true);
        this.user_txt.setVisible(true);
        this.pass_txt.setVisible(true);
        this.Cliente_pic2.setVisible(true);
        this.clie_txt2.setVisible(true);
        this.Gerente_pic.setVisible(false);
        this.Cajero_pic.setVisible(false);
        this.Ejecutivo_pic.setVisible(false);
        this.caje_txt.setVisible(false);
        this.ejec_txt.setVisible(false);
        this.gere_txt.setVisible(false);
        this.Cliente_pic.setVisible(false);
        this.clie_txt.setVisible(false);
        user_txt.setText("No de cuenta: ");
        pass_txt.setText("NIP: ");
        
        
    }//GEN-LAST:event_Cliente_picMouseClicked

    private void Cliente_pic2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cliente_pic2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Cliente_pic2MouseClicked

    private void loguitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loguitoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loguitoMouseClicked

    private void loguito1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loguito1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loguito1MouseClicked

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        String userr,contt;
        
        userr=user.getText();
        contt=password.getText();
        if(b==false){
             if(userr.equals("gerente")&&contt.equals("gerente"))
         {
             JOptionPane.showMessageDialog(null,"Bienvenido a Banco NE","Confirmación de inicio de sesión",JOptionPane.INFORMATION_MESSAGE);             
             new c1_MenuGere().setVisible(true);
             this.setVisible(false);
             user.setText("");
             password.setText("");
         }else{
                  if(userr.equals("ejecutivo")&&contt.equals("ejecutivo"))
         {
             JOptionPane.showMessageDialog(null,"Bienvenido a Banco NE","Confirmación de inicio de sesión",JOptionPane.INFORMATION_MESSAGE);             
             new c2_MenuEjec().setVisible(true);
             this.setVisible(false);
             user.setText("");
             password.setText("");
            }else{
                     if(userr.equals("cajero")&&contt.equals("cajero"))
                    {
                        JOptionPane.showMessageDialog(null,"Bienvenido a Banco NE","Confirmación de inicio de sesión",JOptionPane.INFORMATION_MESSAGE);             
                        new c3_MenuCaje().setVisible(true);
                        this.setVisible(false);
                        user.setText("");
                        password.setText("");
                    }else{
                         JOptionPane.showMessageDialog(null,"Usuario o contrasena incorrectos","Error",JOptionPane.ERROR_MESSAGE);
                     }              
                  }
             }
       
      
        }
        if(b==true){
            buscarusuario(userr);
            buscarnip(userr);
              if(userr.equals(nc1.getText())&&contt.equals(nip1.getText()))
         {
             JOptionPane.showMessageDialog(null,"Bienvenido a Banco NE","Confirmación de inicio de sesión",JOptionPane.INFORMATION_MESSAGE);             
             new c4_MenuClie().setVisible(true);
             
            c4_MenuClie.numcuenta1.setText(nc1.getText());
            c4_MenuClie.nip1.setText(nip1.getText());
            
             this.setVisible(false);
             user.setText("");
             password.setText("");
         }else
         {
             JOptionPane.showMessageDialog(null,"Numero de cuenta o NIP incorrecto","Error",JOptionPane.ERROR_MESSAGE);
             user.setText("");
             password.setText("");
         }
        }
       
        /* else
         {
             JOptionPane.showMessageDialog(null,"Usuario o contraseña incorrecto","Confirmacion de inicio de sesión",JOptionPane.ERROR_MESSAGE);
             user.setText("");
             password.setText("");
         }*/
    }//GEN-LAST:event_AceptarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
       
        this.dispose();
        new b_Usuarios().setVisible(true);
       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        this.dispose();
        new b_Usuarios().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
    public void buscarusuario(String nc){
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");//Permite elegir los controlafdores en los cuales hara la conexion entre java y la base de datos
            Connection con=DriverManager.getConnection("jdbc:odbc:BANCONE","sa","sasa");//Permite realizar la conexion
       Statement stmt=con.createStatement();//Se reconocen las instrucciones de SQL
        ResultSet rs=stmt.executeQuery("SELECT NUM_CUENTA FROM CLIENTE WHERE NUM_CUENTA='"+nc+"'");//mete los valores a la base dedatos
        
        while(rs.next()){
            nc1.setText(rs.getString("NUM_CUENTA"));
            
        }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(d3_NIP.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(d3_NIP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void buscarnip(String nip){
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");//Permite elegir los controlafdores en los cuales hara la conexion entre java y la base de datos
            Connection con=DriverManager.getConnection("jdbc:odbc:BANCONE","sa","sasa");//Permite realizar la conexion
       Statement stmt=con.createStatement();//Se reconocen las instrucciones de SQL
        ResultSet rs=stmt.executeQuery("SELECT NIP FROM CLIENTE WHERE NUM_CUENTA='"+nip+"'");//mete los valores a la base dedatos
        
        while(rs.next()){
            nip1.setText(rs.getString("NIP"));
            
        }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(d3_NIP.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(d3_NIP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(b_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(b_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(b_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(b_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new b_Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JLabel Cajero_pic;
    private javax.swing.JLabel Cajero_pic2;
    private javax.swing.JLabel Cliente_pic;
    private javax.swing.JLabel Cliente_pic2;
    private javax.swing.JLabel Ejecutivo_pic;
    private javax.swing.JLabel Ejecutivo_pic2;
    private javax.swing.JLabel Gerente_pic;
    private javax.swing.JLabel caje_txt;
    private javax.swing.JLabel caje_txt2;
    private javax.swing.JLabel clie_txt;
    private javax.swing.JLabel clie_txt2;
    private javax.swing.JLabel ejec_txt;
    private javax.swing.JLabel ejec_txt2;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel gere_txt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel loguito;
    private javax.swing.JLabel loguito1;
    public static javax.swing.JLabel nc1;
    public static javax.swing.JLabel nip1;
    private javax.swing.JLabel pass_txt;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel seleccion;
    private javax.swing.JTextField user;
    private javax.swing.JLabel user_txt;
    // End of variables declaration//GEN-END:variables
}
