/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancones;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Enrique
 */
public class c2_MenuEjec extends javax.swing.JFrame {

    /**
     * Creates new form c2_MenuEjec
     */
    public c2_MenuEjec() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JLabel();
        loguito1 = new javax.swing.JLabel();
        loguito = new javax.swing.JLabel();
        pago_serv = new javax.swing.JLabel();
        pago_trans = new javax.swing.JLabel();
        crear_c = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        consul2 = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        nc2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 550));
        getContentPane().setLayout(null);

        Menu.setFont(new java.awt.Font("Tahoma", 0, 70)); // NOI18N
        Menu.setForeground(new java.awt.Color(0, 51, 0));
        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/menu.png"))); // NOI18N
        getContentPane().add(Menu);
        Menu.setBounds(250, 80, 300, 100);

        loguito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/logochiqui.png"))); // NOI18N
        loguito1.setToolTipText("EJECUTIVO");
        loguito1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loguito1MouseClicked(evt);
            }
        });
        getContentPane().add(loguito1);
        loguito1.setBounds(20, 20, 90, 70);

        loguito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/ejecutivochiqui.png"))); // NOI18N
        loguito.setToolTipText("EJECUTIVO");
        loguito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loguitoMouseClicked(evt);
            }
        });
        getContentPane().add(loguito);
        loguito.setBounds(680, 30, 90, 70);

        pago_serv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/pagodeservicios.png"))); // NOI18N
        pago_serv.setToolTipText("EJECUTIVO");
        pago_serv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pago_servMouseClicked(evt);
            }
        });
        getContentPane().add(pago_serv);
        pago_serv.setBounds(30, 250, 140, 130);

        pago_trans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/transferencias.png"))); // NOI18N
        pago_trans.setToolTipText("EJECUTIVO");
        pago_trans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pago_transMouseClicked(evt);
            }
        });
        getContentPane().add(pago_trans);
        pago_trans.setBounds(540, 240, 140, 130);

        crear_c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/crearcuenta.png"))); // NOI18N
        crear_c.setToolTipText("EJECUTIVO");
        crear_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crear_cMouseClicked(evt);
            }
        });
        getContentPane().add(crear_c);
        crear_c.setBounds(220, 260, 140, 130);

        text1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text1.setForeground(new java.awt.Color(0, 102, 51));
        text1.setText("Pago de servicios");
        getContentPane().add(text1);
        text1.setBounds(40, 390, 130, 17);

        text.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text.setForeground(new java.awt.Color(0, 102, 51));
        text.setText("Transferencias");
        getContentPane().add(text);
        text.setBounds(560, 390, 110, 17);

        text2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text2.setForeground(new java.awt.Color(0, 102, 51));
        text2.setText("Crear cuenta");
        getContentPane().add(text2);
        text2.setBounds(230, 410, 90, 17);

        consul2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bancones/consultas.png"))); // NOI18N
        consul2.setToolTipText("EJECUTIVO");
        consul2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consul2MouseClicked(evt);
            }
        });
        getContentPane().add(consul2);
        consul2.setBounds(400, 280, 90, 110);

        text3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text3.setForeground(new java.awt.Color(0, 102, 51));
        text3.setText("Consultas");
        getContentPane().add(text3);
        text3.setBounds(410, 410, 80, 17);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 800, 550);

        nc2.setText("jLabel1");
        getContentPane().add(nc2);
        nc2.setBounds(50, 130, 50, 30);

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 153));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jMenu1.setForeground(new java.awt.Color(0, 153, 0));
        jMenu1.setText("OPCIONES");
        jMenu1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jMenuItem2.setText("Atras");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jMenuItem3.setText("Usuario");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setBackground(new java.awt.Color(255, 255, 51));
        jMenuItem1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loguito1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loguito1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loguito1MouseClicked

    private void loguitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loguitoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loguitoMouseClicked

    private void pago_servMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pago_servMouseClicked
         String numcuenta1;
        numcuenta1=JOptionPane.showInputDialog("Numero de cuenta");
        
         buscarusuario(numcuenta1);
       
              if(numcuenta1.equals(nc2.getText()))
         {
             JOptionPane.showMessageDialog(null,"Numero de cuenta correcto","Confirmación de inicio de sesión",JOptionPane.INFORMATION_MESSAGE);             
                new d1_Servicios().setVisible(true);
        d1_Servicios.numcuenta22.setText(""+numcuenta1);
         }else
         {
             JOptionPane.showMessageDialog(null,"Numero de cuenta incorrecto","Error",JOptionPane.ERROR_MESSAGE);
            
         }
        
        
    }//GEN-LAST:event_pago_servMouseClicked

    private void pago_transMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pago_transMouseClicked
        // TODO add your handling code here:
        
          String numcuenta1;
        numcuenta1=JOptionPane.showInputDialog("Numero de cuenta");
        
         buscarusuario(numcuenta1);
       
              if(numcuenta1.equals(nc2.getText()))
         {
             JOptionPane.showMessageDialog(null,"Numero de cuenta correcto","Confirmación de inicio de sesión",JOptionPane.INFORMATION_MESSAGE);             
            new d2_Transferencias().setVisible(true);
        d2_Transferencias.numcuenta4.setText(""+numcuenta1);
         }else
         {
             JOptionPane.showMessageDialog(null,"Numero de cuenta o NIP incorrecto","Error",JOptionPane.ERROR_MESSAGE);
            
         }
    }//GEN-LAST:event_pago_transMouseClicked

    private void crear_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crear_cMouseClicked
        // TODO add your handling code here:
        new d4_CrearC().setVisible(true);
    }//GEN-LAST:event_crear_cMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        this.dispose();
        new b_Usuarios().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void consul2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consul2MouseClicked
        // TODO add your handling code here:
        new d6_Consultas().setVisible(true);
    }//GEN-LAST:event_consul2MouseClicked

    
    
        public void buscarusuario(String nc){
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");//Permite elegir los controlafdores en los cuales hara la conexion entre java y la base de datos
            Connection con=DriverManager.getConnection("jdbc:odbc:BANCONE","sa","sasa");//Permite realizar la conexion
       Statement stmt=con.createStatement();//Se reconocen las instrucciones de SQL
        ResultSet rs=stmt.executeQuery("SELECT NUM_CUENTA FROM CLIENTE WHERE NUM_CUENTA='"+nc+"'");//mete los valores a la base dedatos
        
        while(rs.next()){
            nc2.setText(rs.getString("NUM_CUENTA"));
            
        }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(d3_NIP.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(d3_NIP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(c2_MenuEjec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(c2_MenuEjec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(c2_MenuEjec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(c2_MenuEjec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new c2_MenuEjec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel consul2;
    private javax.swing.JLabel crear_c;
    private javax.swing.JLabel fondo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel loguito;
    private javax.swing.JLabel loguito1;
    private javax.swing.JLabel nc2;
    private javax.swing.JLabel pago_serv;
    private javax.swing.JLabel pago_trans;
    private javax.swing.JLabel text;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    // End of variables declaration//GEN-END:variables
}
