/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancones;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Enrique
 */
public class d1_Servicios extends javax.swing.JFrame {
    private int id=0;
    /**
     * Creates new form d1_Servicios
     */
    public d1_Servicios() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Servicios = new javax.swing.JLabel();
        loguito5 = new javax.swing.JLabel();
        loguito4 = new javax.swing.JLabel();
        loguito3 = new javax.swing.JLabel();
        loguito2 = new javax.swing.JLabel();
        loguito1 = new javax.swing.JLabel();
        loguito = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        text4 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        numcuenta22 = new javax.swing.JLabel();
        nip20 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        saldo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 550));
        getContentPane().setLayout(null);

        Servicios.setFont(new java.awt.Font("Tahoma", 0, 70)); // NOI18N
        Servicios.setForeground(new java.awt.Color(0, 51, 0));
        Servicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/pagodeserviciostxt.png"))); // NOI18N
        getContentPane().add(Servicios);
        Servicios.setBounds(290, 40, 230, 130);

        loguito5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/agua.png"))); // NOI18N
        loguito5.setToolTipText("EJECUTIVO");
        loguito5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loguito5MouseClicked(evt);
            }
        });
        getContentPane().add(loguito5);
        loguito5.setBounds(60, 190, 130, 130);

        loguito4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/predial.png"))); // NOI18N
        loguito4.setToolTipText("EJECUTIVO");
        loguito4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loguito4MouseClicked(evt);
            }
        });
        getContentPane().add(loguito4);
        loguito4.setBounds(640, 360, 130, 130);

        loguito3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/luz.png"))); // NOI18N
        loguito3.setToolTipText("EJECUTIVO");
        loguito3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loguito3MouseClicked(evt);
            }
        });
        getContentPane().add(loguito3);
        loguito3.setBounds(630, 190, 130, 130);

        loguito2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/recargas.png"))); // NOI18N
        loguito2.setToolTipText("EJECUTIVO");
        loguito2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loguito2MouseClicked(evt);
            }
        });
        getContentPane().add(loguito2);
        loguito2.setBounds(80, 350, 130, 130);

        loguito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/logochiqui.png"))); // NOI18N
        loguito1.setToolTipText("EJECUTIVO");
        loguito1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loguito1MouseClicked(evt);
            }
        });
        getContentPane().add(loguito1);
        loguito1.setBounds(20, 20, 90, 70);

        loguito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/pagodeservicios.png"))); // NOI18N
        loguito.setToolTipText("EJECUTIVO");
        loguito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loguitoMouseClicked(evt);
            }
        });
        getContentPane().add(loguito);
        loguito.setBounds(660, 10, 130, 130);

        text1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text1.setForeground(new java.awt.Color(0, 102, 51));
        text1.setText("Luz");
        getContentPane().add(text1);
        text1.setBounds(580, 250, 40, 17);

        text3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text3.setForeground(new java.awt.Color(0, 102, 51));
        text3.setText("Recargas");
        getContentPane().add(text3);
        text3.setBounds(170, 420, 130, 17);

        text4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text4.setForeground(new java.awt.Color(0, 102, 51));
        text4.setText("Predial");
        getContentPane().add(text4);
        text4.setBounds(570, 430, 50, 17);

        text2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text2.setForeground(new java.awt.Color(0, 102, 51));
        text2.setText("Agua");
        getContentPane().add(text2);
        text2.setBounds(180, 250, 130, 17);
        getContentPane().add(numcuenta22);
        numcuenta22.setBounds(70, 130, 0, 0);
        getContentPane().add(nip20);
        nip20.setBounds(50, 160, 0, 0);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 800, 550);

        saldo.setText("jLabel1");
        getContentPane().add(saldo);
        saldo.setBounds(40, 120, 100, 30);

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 153));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jMenu1.setForeground(new java.awt.Color(0, 153, 0));
        jMenu1.setText("OPCIONES");
        jMenu1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jMenuItem2.setText("Atras");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jMenuItem3.setText("Usuario");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setBackground(new java.awt.Color(255, 255, 51));
        jMenuItem1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loguito1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loguito1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loguito1MouseClicked

    private void loguitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loguitoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loguitoMouseClicked

    private void loguito2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loguito2MouseClicked
        // TODO add your handling code here:
        
           float pago,sal;
        id=3;
        pago=Float.parseFloat(JOptionPane.showInputDialog("Cantidad a pagar"));
          buscarsaldo(numcuenta22.getText());
        sal=Float.parseFloat(saldo.getText());
        if(sal<pago){
             JOptionPane.showMessageDialog(null, "No se puede realizar el pago ya que su saldo es insuficiente");  
        }else{
               try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        Connection con=DriverManager.getConnection("jdbc:odbc:BANCONE","sa","sasa");
       // Connection con;
        //con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=BANCONE; user=sa; password=sasa;");
     
        Statement stmt=con.createStatement();
        stmt.executeQuery("insert into CLI_SERVICIO values('"+numcuenta22.getText()+"',"+id+","+pago+",'12/07/2017')");
        }
        catch(Exception e){
            //JOptionPane.showMessageDialog(null,e);
             JOptionPane.showMessageDialog(null, "El pago se realizo con exito");  
        }
        
         try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        Connection con=DriverManager.getConnection("jdbc:odbc:BANCONE","sa","sasa");
       // Connection con;
        //con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=BANCONE; user=sa; password=sasa;");
     
        Statement stmt=con.createStatement();
        stmt.executeQuery("exec retiro "+pago+",'"+numcuenta22.getText()+"'");
        }
        catch(Exception e){

            //JOptionPane.showMessageDialog(null,e);
        }
        }
     
    }//GEN-LAST:event_loguito2MouseClicked

    private void loguito3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loguito3MouseClicked
        // TODO add your handling code here:
           float pago,sal;
        id=2;
        pago=Float.parseFloat(JOptionPane.showInputDialog("Cantidad a pagar"));
         buscarsaldo(numcuenta22.getText());
        sal=Float.parseFloat(saldo.getText());
        
        if(sal<pago){
              JOptionPane.showMessageDialog(null, "No se puede realizar el pago ya que su saldo es insuficiente");    
        }else{
              try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        Connection con=DriverManager.getConnection("jdbc:odbc:BANCONE","sa","sasa");
       // Connection con;
        //con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=BANCONE; user=sa; password=sasa;");
     
        Statement stmt=con.createStatement();
        stmt.executeQuery("insert into CLI_SERVICIO values('"+numcuenta22.getText()+"',"+id+","+pago+",'12/07/2017')");
        }
        catch(Exception e){
 JOptionPane.showMessageDialog(null, "El pago se realizo con exito");  
            //JOptionPane.showMessageDialog(null,e);
        }
        
         try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        Connection con=DriverManager.getConnection("jdbc:odbc:BANCONE","sa","sasa");
       // Connection con;
        //con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=BANCONE; user=sa; password=sasa;");
     
        Statement stmt=con.createStatement();
        stmt.executeQuery("exec retiro "+pago+",'"+numcuenta22.getText()+"'");
        }
        catch(Exception e){

            //JOptionPane.showMessageDialog(null,e);
        }
        }
 
    }//GEN-LAST:event_loguito3MouseClicked

    private void loguito4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loguito4MouseClicked
        // TODO add your handling code here:
           float pago,sal;
        id=4;
        
          buscarsaldo(numcuenta22.getText());
        sal=Float.parseFloat(saldo.getText());
        pago=Float.parseFloat(JOptionPane.showInputDialog("Cantidad a pagar"));
        
        if(sal<pago){
              JOptionPane.showMessageDialog(null, "No se puede realizar el pago ya que su saldo es insuficiente");
        }else{
                  try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        Connection con=DriverManager.getConnection("jdbc:odbc:BANCONE","sa","sasa");
       // Connection con;
        //con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=BANCONE; user=sa; password=sasa;");
     
        Statement stmt=con.createStatement();
        stmt.executeQuery("insert into CLI_SERVICIO values('"+numcuenta22.getText()+"',"+id+","+pago+",'12/07/2017')");
        }
        catch(Exception e){
 JOptionPane.showMessageDialog(null, "El pago se realizo con exito");  
            //JOptionPane.showMessageDialog(null,e);
        }
        
         try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        Connection con=DriverManager.getConnection("jdbc:odbc:BANCONE","sa","sasa");
       // Connection con;
        //con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=BANCONE; user=sa; password=sasa;");
     
        Statement stmt=con.createStatement();
        stmt.executeQuery("exec retiro "+pago+",'"+numcuenta22.getText()+"'");
        }
        catch(Exception e){

            //JOptionPane.showMessageDialog(null,e);
        }
        }
  
    }//GEN-LAST:event_loguito4MouseClicked

    private void loguito5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loguito5MouseClicked
        // TODO add your handling code here:
        float pago,sal;
        id=1;
        buscarsaldo(numcuenta22.getText());
        sal=Float.parseFloat(saldo.getText());
        pago=Float.parseFloat(JOptionPane.showInputDialog("Cantidad a pagar"));
        if(sal<pago){
            JOptionPane.showMessageDialog(null, "No se puede realizar el pago ya que su saldo es insuficiente");
        }else{
                   try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        Connection con=DriverManager.getConnection("jdbc:odbc:BANCONE","sa","sasa");
       // Connection con;
        //con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=BANCONE; user=sa; password=sasa;");
     
        Statement stmt=con.createStatement();
        stmt.executeQuery("insert into CLI_SERVICIO values('"+numcuenta22.getText()+"',"+id+","+pago+",'12/07/2017')");
        }
        catch(Exception e){
 JOptionPane.showMessageDialog(null, "El pago se realizo con exito");  
            //JOptionPane.showMessageDialog(null,e);
        }
        
         try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        Connection con=DriverManager.getConnection("jdbc:odbc:BANCONE","sa","sasa");
       // Connection con;
        //con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=BANCONE; user=sa; password=sasa;");
     
        Statement stmt=con.createStatement();
        stmt.executeQuery("exec retiro "+pago+",'"+numcuenta22.getText()+"'");
        }
        catch(Exception e){

            //JOptionPane.showMessageDialog(null,e);
        }
        
        }
 
        
    }//GEN-LAST:event_loguito5MouseClicked

    
    
      public void buscarsaldo(String nc){
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");//Permite elegir los controlafdores en los cuales hara la conexion entre java y la base de datos
            Connection con=DriverManager.getConnection("jdbc:odbc:BANCONE","sa","sasa");//Permite realizar la conexion
       Statement stmt=con.createStatement();//Se reconocen las instrucciones de SQL
        ResultSet rs=stmt.executeQuery("SELECT SALDO FROM CLIENTE WHERE NUM_CUENTA='"+nc+"'");//mete los valores a la base dedatos
        
        while(rs.next()){
            saldo.setText(rs.getString("SALDO"));
            
        }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(d3_NIP.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(d3_NIP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        this.dispose();
        new b_Usuarios().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(d1_Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(d1_Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(d1_Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(d1_Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new d1_Servicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Servicios;
    private javax.swing.JLabel fondo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel loguito;
    private javax.swing.JLabel loguito1;
    private javax.swing.JLabel loguito2;
    private javax.swing.JLabel loguito3;
    private javax.swing.JLabel loguito4;
    private javax.swing.JLabel loguito5;
    public static javax.swing.JLabel nip20;
    public static javax.swing.JLabel numcuenta22;
    private javax.swing.JLabel saldo;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel text4;
    // End of variables declaration//GEN-END:variables
}
