/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancones;

import static bancones.b_Usuarios.nc1;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Enrique
 */
public class d2_Transferencias extends javax.swing.JFrame {

    /**
     * Creates new form d2_Transferencias
     */
    public d2_Transferencias() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        numcuenta4.setVisible(false);
        nc.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Transferencias = new javax.swing.JLabel();
        loguito1 = new javax.swing.JLabel();
        loguito = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        monto = new javax.swing.JTextField();
        num_cue = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        numcuenta4 = new javax.swing.JLabel();
        nip9 = new javax.swing.JLabel();
        nc = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        saldo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 550));
        getContentPane().setLayout(null);

        Transferencias.setFont(new java.awt.Font("Tahoma", 0, 70)); // NOI18N
        Transferencias.setForeground(new java.awt.Color(0, 51, 0));
        Transferencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/transferenciastxt.png"))); // NOI18N
        getContentPane().add(Transferencias);
        Transferencias.setBounds(150, 80, 510, 100);

        loguito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/logochiqui.png"))); // NOI18N
        loguito1.setToolTipText("EJECUTIVO");
        loguito1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loguito1MouseClicked(evt);
            }
        });
        getContentPane().add(loguito1);
        loguito1.setBounds(20, 20, 90, 70);

        loguito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/transferencias.png"))); // NOI18N
        loguito.setToolTipText("EJECUTIVO");
        loguito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loguitoMouseClicked(evt);
            }
        });
        getContentPane().add(loguito);
        loguito.setBounds(680, 0, 110, 120);

        text2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text2.setForeground(new java.awt.Color(0, 102, 51));
        text2.setText("Monto:");
        getContentPane().add(text2);
        text2.setBounds(130, 330, 130, 17);

        text3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text3.setForeground(new java.awt.Color(0, 102, 51));
        text3.setText("Número de Cuenta:");
        getContentPane().add(text3);
        text3.setBounds(130, 260, 160, 17);
        getContentPane().add(monto);
        monto.setBounds(300, 320, 370, 40);
        getContentPane().add(num_cue);
        num_cue.setBounds(300, 240, 370, 40);

        Aceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Aceptar.setForeground(new java.awt.Color(0, 51, 0));
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(Aceptar);
        Aceptar.setBounds(350, 420, 110, 25);
        getContentPane().add(numcuenta4);
        numcuenta4.setBounds(20, 110, 100, 40);
        getContentPane().add(nip9);
        nip9.setBounds(20, 150, 80, 30);
        getContentPane().add(nc);
        nc.setBounds(30, 160, 80, 20);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_NE/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 800, 550);

        saldo.setText("jLabel1");
        getContentPane().add(saldo);
        saldo.setBounds(20, 150, 34, 14);

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 153));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jMenu1.setForeground(new java.awt.Color(0, 153, 0));
        jMenu1.setText("OPCIONES");
        jMenu1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jMenuItem2.setText("Atras");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jMenuItem3.setText("Usuario");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setBackground(new java.awt.Color(255, 255, 51));
        jMenuItem1.setFont(new java.awt.Font("MV Boli", 0, 12)); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loguito1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loguito1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loguito1MouseClicked

    private void loguitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loguitoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loguitoMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        this.dispose();
        new b_Usuarios().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        buscarusuario(num_cue.getText());
        String numcuent;
        numcuent=num_cue.getText();
        buscarsaldo(numcuenta4.getText());
        float sal,mont;
        mont=Float.parseFloat(monto.getText());
        sal=Float.parseFloat(saldo.getText());
       
        if(numcuent.equals(num_cue.getText())){
            
            if(sal<mont){
              JOptionPane.showMessageDialog(null, "No se puede realizar el pago ya que su saldo es insuficiente");    
        }else{
                 try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        Connection con=DriverManager.getConnection("jdbc:odbc:BANCONE","sa","sasa");
       // Connection con;
        //con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=BANCONE; user=sa; password=sasa;");
     
        Statement stmt=con.createStatement();
        stmt.executeQuery("insert into TRANSFERENCIAS values('"+numcuenta4.getText()+"','"+nc.getText()+"',"+monto.getText()+",'12/07/2017')");
        }
        catch(Exception e){

            //JOptionPane.showMessageDialog(null,e);
        }
            
               try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        Connection con=DriverManager.getConnection("jdbc:odbc:BANCONE","sa","sasa");
       // Connection con;
        //con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=BANCONE; user=sa; password=sasa;");
     
        Statement stmt=con.createStatement();
        stmt.executeQuery("exec retiro "+monto.getText()+",'"+numcuenta4.getText()+"' ");
        }
        catch(Exception e){

            //JOptionPane.showMessageDialog(null,e);
        }             
             try{
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        Connection con=DriverManager.getConnection("jdbc:odbc:BANCONE","sa","sasa");
       // Connection con;
        //con= DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=BANCONE; user=sa; password=sasa;");
     
        Statement stmt=con.createStatement();
        stmt.executeQuery("exec deposito "+monto.getText()+",'"+nc.getText()+"' ");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"La transaccion se hizo con exito\nEl recibo de la transaccion fue enviado a su correo electronico");
            //JOptionPane.showMessageDialog(null,e);
        }
             
            
            
            
            } 
          
            
          
            
            
        }
        
        
        
    }//GEN-LAST:event_AceptarActionPerformed

     public void buscarsaldo(String nc){
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");//Permite elegir los controlafdores en los cuales hara la conexion entre java y la base de datos
            Connection con=DriverManager.getConnection("jdbc:odbc:BANCONE","sa","sasa");//Permite realizar la conexion
       Statement stmt=con.createStatement();//Se reconocen las instrucciones de SQL
        ResultSet rs=stmt.executeQuery("SELECT SALDO FROM CLIENTE WHERE NUM_CUENTA='"+nc+"'");//mete los valores a la base dedatos
        
        while(rs.next()){
            saldo.setText(rs.getString("SALDO"));
            
        }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(d3_NIP.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(d3_NIP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
     
     
    public void buscarusuario(String nc1){
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");//Permite elegir los controlafdores en los cuales hara la conexion entre java y la base de datos
            Connection con=DriverManager.getConnection("jdbc:odbc:BANCONE","sa","sasa");//Permite realizar la conexion
       Statement stmt=con.createStatement();//Se reconocen las instrucciones de SQL
        ResultSet rs=stmt.executeQuery("SELECT NUM_CUENTA FROM CLIENTE WHERE NUM_CUENTA='"+nc1+"'");//mete los valores a la base dedatos
        
        while(rs.next()){
            nc.setText(rs.getString("NUM_CUENTA"));
            
        }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(d3_NIP.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(d3_NIP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(d2_Transferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(d2_Transferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(d2_Transferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(d2_Transferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new d2_Transferencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JLabel Transferencias;
    private javax.swing.JLabel fondo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel loguito;
    private javax.swing.JLabel loguito1;
    private javax.swing.JTextField monto;
    private javax.swing.JLabel nc;
    public static javax.swing.JLabel nip9;
    private javax.swing.JTextField num_cue;
    public static javax.swing.JLabel numcuenta4;
    private javax.swing.JLabel saldo;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    // End of variables declaration//GEN-END:variables
}
